version: '3'

services:

  caddy:
    ports: 
      - 2015:2015
      - 2019:2019

  ngrok:
    image: ngrok/ngrok
    restart: unless-stopped
    hostname: ngrok
    depends_on:
      caddy:
        condition: service_healthy
    networks:
      - mediator-network
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http caddy:2015 --log stdout
    # ports: # Uncomment to access ngrok outside of containers
    #   - 4040:4040 # admin port
    healthcheck:
      test: /bin/bash -c "</dev/tcp/ngrok/4040"
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 5

  mediator:
    depends_on:
        # mediator-controller:
        #   condition: service_healthy
      db:
        condition: service_healthy
      ngrok:
        condition: service_healthy
